baseURL: "https://merinhunter.github.io/master-thesis-web/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Trabajo Fin de Máster
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        # menu:
        #     main:
        #         - name: Archive
        #           url: archives
        #           weight: 5
        #         - name: Search
        #           url: search/
        #           weight: 10
        #         - name: Tags
        #           url: tags/
        #           weight: 10
        #         - name: WiKi
        #           url: https://github.com/adityatelange/hugo-PaperMod/wiki/
        #         - name: Discord
        #           url: https://discord.gg/ahpmTvhVmp

    # fr:
    #     languageName: ":fr:"
    #     languageAltTitle: French
    #     weight: 2
    #     title: PaperModL2
    #     taxonomies:
    #       category: FRcategories
    #       tag: FRtags
    #       series: FRseries
    #     profileMode:
    #         enabled: true
    #         title: PaperMod
    #         imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
    #         imageTitle: ProfileMode image
    #         # imageWidth: 120
    #         # imageHeight: 120
    #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Profile Mode
    #               url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: FRTags
    #               url: frtags
    #               weight: 10
    #             - name: FRCategories
    #               url: frcategories
    #               weight: 10
    #             - name: FRSeries
    #               url: frseries
    #               weight: 10
    #             - name: NullLink
    #               url: "#"

    # fa:
    #     languagedirection: rtl
    #     weight: 3
    #     title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     taxonomies:
    #       category: FAcategories
    #       tag: FAtags
    #       series: FAseries
    #     menu:
    #         main:
    #             - name: FATags
    #               url: fatags
    #               weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Grimoirebots"
        Content: >
            **Grimoirebots** es un complejo sistema de análisis de repositorios git que, de forma automática, obtiene y genera datos sobre el desarrollo de software, permitiendo su uso mediante la creación de métricas y gráficas<br/><br/>

            - # Resumen<br/><br/>

            - El desarrollo de software es una disciplina que ha sufrido una gran evolución en los últimos años. Hoy en día, esta materia no está ligada única y exclusivamente a lo que su nombre sugiere, sino que abarca una infinidad de actividades diferentes que conforman un ecosistema cada vez más grande y complejo. Estudiar estos entornos se ha convertido en una auténtica ciencia, donde la analítica de los datos asociados a ella posibilita un mayor entendimiento del desarrollo de software.<br/><br/>

            - Para este fin, existen herramientas como GrimoireLab que permite la obtención automática de estos datos. Sin embargo, su uso no es tan sencillo, y esto supone en ocasiones una limitación para perfiles no técnicos.<br/><br/>

            - En este contexto, este **Trabajo de Fin de Máster** se centra en el desarrollo de un sistema que facilite el uso de GrimoireLab, primero mediante el estudio e investigación de herramientas ya existentes para este fin, luego mediante el el diseño e implementación de un sistema automatizado de obtención de datos referentes al desarrollo de software, y finalmente mediante la integración de este sistema con herramientas de visualización de datos para la construcción de métricas y gráficas que ayuden a comprender mejor este ecosistema.

    socialIcons:
        - name: github
          url: "https://github.com/merinhunter/grimoirebots"
        - name: youtube
          url: "https://youtu.be/vmRFruqXS-I"
        - name: cv
          title: Master Thesis
          url: "master-thesis.pdf"
        - name: cv
          title: Master Thesis Slides
          url: "master-thesis-slides.pdf"

    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
